Initial changes for jupyterlab 2.1.5 support
Remaning build errors:

src/lib/NotebookUtils.tsx:321:67 - error TS2339: Property 'IKernelConnection' does not exist on type 'typeof import("/home/david/kale/labextension/node_modules/@jupyterlab/services/lib/kernel/kernel")'.

321     let options: Kernel.IKernelConnection.IOptions = await Kernel.IKernelConnection.spec.then(kernelSpecs => {
                                                                      ~~~~~~~~~~~~~~~~~

src/lib/NotebookUtils.tsx:321:95 - error TS7006: Parameter 'kernelSpecs' implicitly has an 'any' type.

321     let options: Kernel.IKernelConnection.IOptions = await Kernel.IKernelConnection.spec.then(kernelSpecs => {
                                                                                                  ~~~~~~~~~~~

src/lib/NotebookUtils.tsx:327:25 - error TS2339: Property 'IManager' does not exist on type 'typeof import("/home/david/kale/labextension/node_modules/@jupyterlab/services/lib/kernel/kernel")'.

327     return await Kernel.IManager.startNew(options).then(_kernel => {
                            ~~~~~~~~

src/lib/NotebookUtils.tsx:327:57 - error TS7006: Parameter '_kernel' implicitly has an 'any' type.

327     return await Kernel.IManager.startNew(options).then(_kernel => {
                                                            ~~~~~~~

src/lib/NotebookUtils.tsx:450:36 - error TS2339: Property 'kernel' does not exist on type 'ISessionContext'.

450       notebookPanel.sessionContext.kernel,